### ISSUE TITLE
About Racing Format

### ISSUE THREAD

**Issue by AUnal7** [BLG638-Project/final-project-2022#10]
Hello,

Will the cars race individually or together? Thanks in advance.

**Comment by resuldagdanov** [comment]
Dear @AUnal7,

Before submission of the trained models to the final racing competition, participants could use other vehicles as desired. You can take a look at spawning other vehicles functions in _**training_example/simstarEnv.py**_ script.

Before the deadline is finished, participants should submit their best-trained models in given sensor configurations.

Final racing format (high-level):
* Each team's submitted torch models will be raced on the same racing track individually to calculate the **time to finish the track** (lap-time) in seconds.
* After individual lap-time evaluations are finished, submitted models of all teams will be raced **against each other** on the same track simultaneously.
* The initial vehicle positions of the teams will be ordered according to their individual lap-time performances.
* This final simultaneous racing will determine the winners.
(note: number of laps for the final racing will soon be determined)
