### ISSUE TITLE
Mac Simstar installation

### ISSUE THREAD

**Issue by ecemmine** [BLG638-Project/final-project-2022#11]
I can't install Simstar on Mac. How can I solve this issue?

**Comment by resuldagdanov** [comment]
Türkçe:

Şimdilik Mac işletim sistemi için bir destek yoktur. Macbook'a ikinci işletim sistemi olarak Windows kurmayo deneyebilirsiniz.
Teşekkürler.

-----------------------------------------------------

English:

Mac operating system is not supported right now. You can try to install Windows on Mac as a dual boot.
Thanks.

-----------------------------------------------------

You can take a look at the following links to install windows on mac:
* https://support.apple.com/en-us/HT201468 
* https://www.laptopmag.com/articles/dual-boot-windows-macos
