### ISSUE TITLE
Yarış Pisti

### ISSUE THREAD

**Issue by afurkany** [BLG638-Project/final-project-2022#13]
Merhabalar,

Yarış pisti olarak sadece tek bir pist mi olacak? Yoksa SimStar'ı açtığımızda karşımıza çıkan pist dışında bir pist de yarış günü olabilir mi?

Teşekkür ederim.

**Comment by afurkany** [comment]
Tekrar merhaba,

Sormayı unuttum, ayrıca kaç turluk bir yarış olacak?

Teşekkür ederim.

**Comment by resuldagdanov** [comment]
Türkçe:

Sayın @afurkany,
1) Yarış gününde de size **sunulan pist** olacak. Pistteki tüm elementler ve boyutları _sabit_ olacak.
2) Tur sayısı sonraki günlerde hoca tarafından _duyurulacak_. Hala **kesinleştirilmedi**.
Teşekkürler.

-----------------------------------------

English:

Dear @afurkany,
1) The competition will be held on the **same track** that is given to you. Every static element on the track will be the _same size_ during the competition as it is given.
2) The number of laps during the final competition is **not determined** yet but will be _announced_ soon by the professor.
Thanks.
