### ISSUE TITLE
Environment code (simstarEnv.py) manipulation

### ISSUE THREAD

**Issue by afurkany** [BLG638-Project/final-project-2022#14]
Merhabalar,

Environment'i sensörler ve araç dinamikleri dışında manipüle edebilir miyiz?

- Özellikle belirtmem gerekirse sensör ve araç dinamikleri kısımları ile oynamadan reward veya punishment kurallarını değiştirebilir miyiz? 
- Ayrıca eğitim esnasında rakip olarak kendi eğittiğimiz modelleri atamak için "add_opponent" fonksiyonunu değiştirmemiz mümkün mü?

Teşekkür ederim.

**Comment by resuldagdanov** [comment]
Türkçe:

Sayın @afurkany,

Çevredeki **statik değişkenler** (örneğin yol genişliği, fps, araba boyutları, vb.) ve **arabaların, sensörlerin kalibre sabitleri** (kalibrasyonlar, sensör konumları, açıları, görüş alanları, vb.) değiştirilmemesi gerekmektedir. Çünkü final yarışmasında da size subulan bu sabit değerler kullanılacaktır; eğer farklı bir konfigürasyonlarda eğitim yaparsanız final yarışında başarısız olmanız büyük ihtimaldir.

Ödül fonksiyonunda, cezalandırma şartlarında istediğiniz gibi değişiklik yapabilirsiniz. Yalnız dikkat etmeniz gereken nokta, tüm değişiklikleri yaptığınız ve yapmadığınız kod kısımlarının hepsini proje dosyasına yüklemeniz gerekmektedir.

Eğer diğer araçları da eğitilmiş model yüklemek isterseniz simstarEnv.py satır **227-234**:

> self.main_vehicle = self.client.spawn_vehicle(
> actor=self.road,
> distance=self.ego_start_offset,
> lane_id=self.ego_lane_id,
> initial_speed=0,
> set_speed=self.set_ego_speed,
> vehicle_type=simstar.EVehicleType.F1Racing)

kısımlarını inceleyebilir ve örnekteki gibi kullanabilirsiniz.
Teşekkürler.

**Comment by afurkany** [comment]
Sayın @resuldagdanov

Hızlı geri dönüşünüz için teşekkür ederim. Belirttiğiniz kısımları inceleyeceğim.
