### ISSUE TITLE
About Tracks

### ISSUE THREAD

**Issue by AUnal7** [BLG638-Project/final-project-2022#15]
Merhaba,

Final yarışı farklı bir pistte mi yapılacak? Bir de Simstar'da farklı pistleri çağırabiliyorsak nasıl çağırabiliyoruz?

Şimdiden teşekkürler.

**Comment by resuldagdanov** [comment]
Türkçe:

Sayın @AUnal7,

* Burada https://github.com/BLG638-Project/final-project-2022/issues/13  da belirtildiği gibi yarış pisti ile size sunulan pist aynı olacak. Yeni pist yüklenmeyecek ve yeni pist sürprizleri ile karşılaşılmayacak. :)

* SimStar'da farklı pistler çağırılabiliyor ancak bunu için sizin pist dosyalarına (Maps) erişmeniz lazım. Bu proje ve yarışma için size **sadece 1 pist** sunulacak; farklı pistlere erişim olmayacak.

Teşekkürler.

---------------------------------------

English:

Dear @AUnal7,

* As discussed and closed in issue https://github.com/BLG638-Project/final-project-2022/issues/13, you will be given only one racing track and in the final competition, all trained models will be evaluated on the same track.

* Different racing tracks could be uploaded to SimStar; however, the map files are required. We have not shared any other map files to this competition as all the training and evaluation for this project/competition will be held on only one given racing track.

Thanks.
