### ISSUE TITLE
Environment ve Training Hakkında Genel Sorular

### ISSUE THREAD

**Issue by yildize** [BLG638-Project/final-project-2022#16]
1. Train ve simstarEnv modulleri içerisine kabaca baktığımda ego dışındaki vehicles'ı yani opponent'i kontrol eden modelin ne olduğunu tam anlayamadım, bu rule-based bir şey mi yoksa daha önce train edilmiş bir başka model mi? Ve ben bunları nasıl replace edebilirim? Kısaca diğer araçlara istediğim model'i nasıl load edebilirim?

2. Train module'ü içerisinde training mode'unu belirleyen bir global, TRAIN var. Bunu 0 yapınca evaluation mode'u oluyor sanıyorum. Bir de ayrıca evaluate.py module'ü söz konusu. Bunların farkı ne?

3. Transfer learning yapmak için train.py içerisinde hazır bir yapı göremedim, daha önce train edilmiş bir modelin üzerine yeni training yapmak için load_model()'i kendimiz mi çağırmamız gerekiyor?

4. Environment'ın progress değişkeni speed ile bir angle difference çarpımıyla hesaplanıyor burada kullanılan "angle" tam olarak neyi temsil ediyor?

5. Benzer şekilde road deviation tespiti için trackPos>=0.9 koşulu kullanılmış, trackPos tam olarak neyi temsil ediyor, bu ve benzeri kritik variables'ın ne anlama geldiğini görebileceğimiz bir kaynak var mı?

6. simstarEnv module'ü içerisinde reward hesabının yapıldığı yerde bir collision variable'ı kullanılıyor, buna bağlı olarak reward düşürülüyor ancak farkettim ki bu flag her zaman false geliyor, dolayısıyla collision olsa da herhangi bir reward düşüşü yaşanmıyor, burada ne kaçırıyorum tam olarak?

**Comment by resuldagdanov** [comment]
Türkçe:

Sayın @yildize,

1. Ego aracı dışındaki araçların modeli (_Intelligent Driving Model_) IDM'dir. Bu kural tabanlı bazı fonksiyonlardan oluşan model. Aynı zamanda içerisinde kural tabanlı şerit değiştirme kurallı model eklenmiştir. Daha fazla detay için buraya (https://mtreiber.de/MicroApplet/IDM.html) bakabilirsiniz. Bu altyapı Eatron tarafından geliştirildi ve SimStar API'ına gömünü olarak **kapalı kutu** sunuldu. Diğer araçların kontrolünü eğitilmiş model ile kontrol etmek isterseniz https://github.com/BLG638-Project/final-project-2022/issues/14 yorumlara bakabilirsiniz.

> self.client.spawn_vehicle()

Kısacası bu fonksiyonu kullanarak ego aracının spawn edilişi gibi diğer araçları da ekleyebilirsiniz.

2. evaluate.py ve train.py (TRAIN=0) aralarında _pek fark yok_. Başlıca farklılıklar şunlar:
a) evaluate.py kodu tensorboard'da logları kaydetmiyor.
b) evaluate.py kodunda tüm araçların kontrolünü eğitilmiş modeller ile kontrol etmenin örneği var (satır **93-97**):

> if CONTROL_OTHER_AGENTS:
>         opponent_agent = Model(
>             env=env, params=hyprm, n_insize=insize, n_outsize=outsize
>         )
>         load_checkpoint(opponent_agent)

c) final yarışmasın'da da tüm araçlara eğitilmiş modellerin yüklenmesi _evaluate.py_ kodundaki düzenlemelere benzer olacak.

3. Kendiniz load_model() fonksiyonunu kullanarak _transfer learning_ yapabilirsiniz. Bu düzenlemeler kolaylıkla yapılabildiği için direkt bir transfer learning örneği _verilmemiştir_.

4. **angle**: https://github.com/BLG638-Project/final-project-2022/blob/main/README.md (sensors-angle sensor)'da belirtildiği gibi yolun merkezinden arabanın yönelim açısının değişimini temsil ediyor. Eğer araba yolun gidiş yönünde paralel yönelmişse bu açı değeri 0 _radyan_ gelir.

5. **trackPos**: https://github.com/BLG638-Project/final-project-2022/blob/main/README.md (sensors-track position sensor)'da belirtildiği gibi bu sensör yolun merkezinden enlemsel olarak kaymasını temsil ediyor. Eğer araba yolun tam ortasında ise 0 _metre_ gelir. **Not:** Network'e beslenmeden önce normalize (0-1 arasına) edilmiştir.

6. Geçmiş yıllarda arabaların birbirleriyle çarpışmalarından dolayı ceza alırdı. Bu sene bunun gibi kaza olaylarının tespiti veilgili cezalandırmayı yapmak/ayarlamak öğrencilere bırakılmıştır. _Opponents Sensor_'ü çıktısını kullanarak çarpışmalar/kazalar tespit edilebilir. Bu sensörün çalışma mantığını anlamak için https://github.com/BLG638-Project/final-project-2022/blob/main/README.md (sensors-opponents sensor) inceleyebilirsiniz.

Teşekkürler.

**Comment by yildize** [comment]
Açıklamalar için teşekkürler. Ekstra bir kaç sorum daha olacaktı.

1. Şuanki yapıda, PPO gibi algoritmalar için kullanmak üzere vectorized environments kullanmak mümkün mü? Halihazırda böyle bir paralleleştirme sunulmuş mu? 
2. Training'i hızlandırmak amacıyla simstar görselleştirme ekranı olmadan eğitim yapmak mümkün mü?
3. Environment içerisinde initial speed yanında "set_ego_speed" kullanılmış ve default 60 olarak set edilmiş, bunun işlevi tam olarak nedir?
4. Ego için initial yaw set edebiliyor muyuz?

Teşekkürler.

**Comment by resuldagdanov** [comment]
Sayın @yildize,

1. Paralleleştirme açık olarak sunulmamıştır. Eğer parallel eğitimler yapmak isteniliyorsa öğrencilerin kendilerini bunu yazmaları gerekmektedir. Bu projenin ana amacı minimum koşulları sunmak ve projede öğrencilerden beklenen de bu minimum koşulların üzerine ne kadar ekleme, inovatiflik ve yaratıcılık katıldığını ölçmektir.

2. Eğitimleri rendersiz gerçekleştirebilmek için Readme (https://github.com/BLG638-Project/final-project-2022/blob/main/README.md)'de de belirtildiği gibi aşağıdaki konutu kullanarak SimStar rendersiz açılabilir.

   > ./Simstar.sh -nullrhi

3. simstarEnv.py kodundali "**set_ego_speed**" değişkeninin amacı eğer ego aracını da bir botlar (IDM) gibi kullanılmak istendiğinde ego aracının hedef hızını belirtmektedir. Halihazırda sunulan ego aracını bir '_RL agent_' olarak kullanıldığı zaman bu "**set_ego_speed**" değişkeninin bir işlevi _yoktur_.

4. Ego aracının başlangıç yönelme açısını değiştirebilmek simstarEnv.py kodundaki satır **294-299:**

   > ent = self.client.spawn_vehicle_to(
   >                             vehicle_pose=self.opponent_poses[i],
   >                             initial_speed=0,
   >                             set_speed=self.agent_speeds[i],
   >                             vehicle_type=simstar.EVehicleType.F1Racing,
   >                         )

_vehicle_pose_ argümanına **yaw** (yönelme) açısı verebilirsiniz. Örnek kod için _evaluate.py_ kodunda aşağıdaki kısımlara bakabilirsiniz.

    > AGENT_LOCATIONS = [
    >     simstar.PoseData(1288.012085, -887.185735, yaw=-3.08),
    > ]
  
Teşekkürler.

**Comment by yildize** [comment]
Tekrar merhaba, anlayamadığım bir nokta var. Örneklerde ego spawn etmek için hep  spawn_vehicle() kullanılırken opponents için spawn_vehicle_to() kullanılmış. Bunların farkı nedir tam olarak? İkisi de herhangi bir araç için kullanılabilir mi? spawn_vehicle fonksiyonu için yaw belirtemiyoruz gibi duruyor ayrıca bir "actor" argümanı söz konusu bu actor argümanı bir yerde "self.road" olarak assign edilirken bir başka yerde "self.main_vehicle" olarak assign edilmiş ve self.road ile self.main_vehicle tamamen alakasız yapılar değil mi? Bu fonkisyonların yapısını çok kısaca açıklamanız mümkün müdür acaba? 

Teşekkürler :)

**Comment by resuldagdanov** [comment]
Sayın @yildize,

* Dediğiniz gibi ego arabasının oluşturulmasında **client.spawn_vehicle()** fonksiyonu kullanılıyor. Aynı şekilde diğer IDM (bot) araçları için de bu **client.spawn_vehicle()** fonksiyonunu kullanabilirsiniz.
* Arabaların başlangıç yönelimlerini belirtebilmek için ise **client.spawn_vehicle_to()** fonksiyonu kullanılıyor çünkü bu fonksiyonun _vehicle_pose_ argümanı vardır. Bu _vehicle_pose_ argümanı ile araçların başlangıç yönelimini ayarlayabiliyorsunuz.
* Ego aracı **dahil** tüm araçları **client.spawn_vehicle_to()** fonksiyonu ile oluşturabilirsiniz. Ama eğer bir actor'ü (örneğin ego araba) göreceli alarak araçların başlangıç konumlarını ayarlamak isterseniz **client.spawn_vehicle()** fonksiyonunu kullanabilirsiniz.

**Not:** ego aracı dahil tüm arabaları aşağıdaki örnekteki gibi oluşturabilirsiniz.
>   new_agent = self.client.spawn_vehicle_to(
>        vehicle_pose=self.opponent_poses[i],
>        initial_speed=0,
>        set_speed=self.agent_speeds[i],
>        vehicle_type=simstar.EVehicleType.F1Racing)

Teşekkürler.
