### ISSUE TITLE
Simstar Simulation Speed

### ISSUE THREAD

**Issue by afurkany** [BLG638-Project/final-project-2022#19]
Merhabalar,

Simstar ortamında simulasyonu train.py kodunda belirtilen hızın üzerinde yapmamızın bir yolu var mı? Demek istediğim Kod içerisinde 39 ve 40. satırlarda belirtilen (altta da görebilirsiniz) ayarın üzerine çıkmamızın bir yolu var mı?

times speeding up the training process [1-6]
SPEED_UP = 6

Environment  reset olduğunda hep en baştan eğitime başlıyoruz. Harita epey büyük olduğu için bir episode'u bitirmek çok uzun sürüyor. Bu nedenle kodda 15000 kadar episode tanımlanmış olsa da en fazla 3000 civarına kadar çıkabiliyorum ve train ettiğimde bütün haritayı bitirebilecek bir agent şu ana kadar yaratamadım.

Şu an CPU ile çalışıyorum. DL çalışmaları özelinde daha önce az da olsa GPU ile çalıştım fakat hiç RL özelinde çalışmadım. CPU'dan GPU'ya geçmek belirttiğim hız sorunu konusunda verimli ve uygulaması kolay olur mu?

Veya Simstar'ı train ederken arka planda çalıştırıp training hızını arttırmamız mümkün mü?

Teşekkür ederim.

**Comment by resuldagdanov** [comment]
Sayın @afurkany,

Aslında yarışmanın bir diğer amaçlarından biri de baştan sona kadar tüm pisti öğrenecek RL ajanını eğitmenin zor olduğunu görmek gibi. Sebebi uzun sürüyor ve felaket unutma (catastrophic forgetting) olma ihtimali yükseliyor. Literatürde bulunan farklı yöntemler (curriculum learning, transfer learning, hierarchical learning, meta RL, parameter sharing, distillation, representation learning, e.g.) deneyebilirsiniz.

SimStar'da eğitim yaparken rendersiz işlemleri yapmak eğitimi daha hızlandırabilir. Bunun için aşağıdaki komut satırı ile SimStar'ı açabilirsiniz.

> ./Simstar.sh -nullrhi

Onun haricinde daha da hızlandırmak bazı environment şartlarından dolayı mümkün olmayabilir.

Aşağıdaki komut ile farklı portlarda farklı SimStar environment açabilirsiniz.

> ./SimStar.sh -nullrhi -api_port=9090

Eğitim yapacağınız zaman da:

> python train.py 9090

Bu eğitim calismaya devam ederken, diger deneylerinizi baska SimStar'larda yapmaya devam edebilirsiniz (farkli port sayısını kullanarak).

Başka bir çözün olarak ise pistin farklı noktalarından başlayarak eğitimleri gerçekleştirebilirsiniz.

Teşekkürler.

**Comment by afurkany** [comment]
Sayın **@resuldagdanov** 

Cevabınız için çok teşekkür ederim.

Evet dediğiniz gibi literatürü biraz incelediğimde bazı çalışmalarda curriculum learning uygulandığını gördüm. Ben de bu şekilde denemeye çalışıyorum.

Render olmadan işlem yapmak hızı arttırabilir.  Bunu denememiştim, deneyeceğim.

Benim de aklımdaki son fikir sizin son söylediğiniz, farklı noktalardan başlayarak eğitim yapmak konusuydu. Onu da deneyeceğim.

Umarım bunlardan bir veya birkaçı sorunu çözmeme yardımcı olur.

Teşekkür ederim.

**Comment by afurkany** [comment]
Sayın @resuldagdanov

Actor aracını environment'ı reset ederken pistin başka yerlerinden başlatmak için kod içerisinde bazı aramalar yaptım.

Actor aracı için reset fonksiyonunda alttaki kısım yer alıyor.

`self.main_vehicle = self.client.spawn_vehicle(
            actor=self.road,
            distance=self.ego_start_offset,
            lane_id=self.ego_lane_id,
            initial_speed=0,
            set_speed=self.set_ego_speed,
            vehicle_type=simstar.EVehicleType.F1Racing,
        )`

Bu kısımdaki distance değeri girdisi olan `self.ego_start_offset` değerini çok arttırdığım zaman hata alıyorum. Opponent vehicle'lar için olan `spawn_vehicle_to() `fonksiyonunu denediğim zaman ise araç actor olmaktan çıkıyor ve kural bazlı araçlar gibi çalışmaya başlıyor.

Actor aracın pistteki konumunu değiştirmek için başka bir öneriniz var mı? Örneğin, pistin yarısından eğitime başlatmak olarak düşünebilirsiniz.

Ayrıca iki sorum olacak. Sizin eğittiğiniz default_model'i eğitirken bahsettiğim konu ile ilgili bir değişiklik yaptınız mı? Bir de eğitim sırasında cpu mu yoksa gpu mu kullandınız?

Teşekkür ederim.

**Comment by resuldagdanov** [comment]
Merhaba,

**Default Model** eğitiminde direkt `train.py` kodu çalıştırılmıştır. Bu kod içerisinde yapılan tüm değişikliklere buradan https://github.com/BLG638-Project/final-project-2022/blob/main/training_example/default_model/parameters.txt ulaşabilirsiniz.

Teşekkürler.

**Comment by resuldagdanov** [comment]
* `self.ego_start_offset` değeri çok arttırılınca arabaların yoldan çıkarak başlamasına sebebiyet veriyor olabilirsiniz ve bu da hata ile sonuçlanıyor olabilir ya da arabaları aynı konumda üst üste oluşturmaya çalışıyor olabilir.
* Ego aracı için `self.client.spawn_vehicle()` fonksiyonunu kullanabilirsiniz. Çünkü `self.client.spawn_vehicle_to()` fonksiyonu arabaya IDM model yüklüyor olabilir ve tekrardan **API** moduna almak gerekebilir.

**Comment by resuldagdanov** [comment]
Merhaba,

SimStar arayüzünde araçları haritaya eklemeden önce bir noktaya tıklayıp konumunu alabilirsiniz veya klavye kontrolü (https://github.com/BLG638-Project/final-project-2022/commit/c2de0417b6539983c4c79a7e89920bf92a4fc482) ile arabayı kontrol edip istediğiniz konumun enlem, boylem ve yönelme bilgilerini elde edebilirsiniz.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/60505033/174278137-287fc9a6-eafc-4354-8dd2-1bbe499344c7.png)

Aşağıdaki fonksiyon ile araçları konumlandırabilirsiniz:

```python
self.main_vehicle = self.client.spawn_vehicle_to(
                    vehicle_pose=simstar.PoseData(88.006317, -131.966187, yaw= np.deg2rad(146)),
                    initial_speed=0,
                    set_speed=0,
                    vehicle_type=simstar.EVehicleType.F1Racing)
```

Teşekkürler.
