### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by fatma262** [BLG638-Project/final-project-2022#20]
Merhaba,

Projede docker kullanabiliyor muyuz?

**Comment by fatma262** [comment]
Merhaba @resuldagdanov 

Ben train.py kodunu çalıştıramadım. simstar ı anaconda da oluşturdum, aktif ettim, requirements yükledim python setup.py install komutunu da çalıştırdım. vs code ve win kullanıyorum. vs code simstar ı aktif ettim. Fakat train.py kodunu çalıştırınca AttributeError: module 'torch' has no attribute 'Tensor' hatasını alıyorum. pip list yazıp simstar'ın içine bakınca da torch 1.11.0 var gözüküyor.

Dikkatimden kaçan ne var burada?

**Comment by resuldagdanov** [comment]
Sayın @fatma262,

SimStar'ı Docker'da çalıştırmak için örnek bir projemiz halihazırda **mevcut değildir** ve SimStar'ın Docker'da çalışmasına engel olan bir durumu **yoktur**.

Teşekkürler.

**Comment by resuldagdanov** [comment]
Sayın @fatma262,

Python > 3.6 versiyon kullandığınızdan emin olmak lazım. Sizin aldığınız hata aşağıdaki linkteki ile aynı olabilir.

> https://stackoverflow.com/questions/47317141/pytorch-attributeerror-module-torch-has-no-attribute-tensor 

Burada anlatılanlara bakabilir misiniz?

Teşekkürler.

**Comment by fatma262** [comment]
Sayın @resuldagdanov 

Teşekkür ediyorum.
