### ISSUE TITLE
Ubuntuda çalışma hatası

### ISSUE THREAD

**Issue by muraatozbek** [BLG638-Project/final-project-2022#22]
Merhaba,
 
Ubuntu bilgisayarda simstar'i çalıştırmak istediğimde hata alıyorum. Sorunu çözemedim.
 
Teşekkür ederim
![Screenshot from 2022-06-15 23-56-29](https://user-images.githubusercontent.com/52512556/173929454-ef9630d6-4cb2-4b4b-841f-2b884ed6df52.png)

**Comment by fatma262** [comment]
Bu hatayı ben de aldım windowsta. Send and restart deyince düzeldi.

**Comment by resuldagdanov** [comment]
Sayın @muraatozbek,

@fatma262 dediği gibi yapınca hata çözülmesi lazım.
Hata düzelince bu issue kapatılabilir.

Teşekkürler.

**Comment by muraatozbek** [comment]
Merhaba,
 
 Yardımınız için teşekkür ederim. Fakat daha önce denemiştim dediğinizi bu seferde "RPC port in use, select another port" yazısı çıkıyor."Ok" tiklayincada direkt olarak kapanıyor.
