### ISSUE TITLE
Sensörler Hk.

### ISSUE THREAD

**Issue by yildize** [BLG638-Project/final-project-2022#23]
Emin olmamakla birlikte sensörlerde kaydadeğer seviyede bir gecikme olduğu konusunda şüphelerim var. Bu beklenen bir durum mu? Gecikme olup olmadığından nasıl emin olabiliriz?

**Comment by resuldagdanov** [comment]
Sayın @yildize,

* Sensörler sabit frekansta çalışmaktalar ve bu frekans eğitim boyunca değişmemelidir (değişmemektedir).

* Manuel kullanmak için https://github.com/BLG638-Project/final-project-2022/commit/c2de0417b6539983c4c79a7e89920bf92a4fc482 commit'e bakabilirsiniz.

* Arabayı klavye ile kullanırken sensör çıktılarını yazdırabilirsiniz.

* SimStar'ın v2.1.1 versiyonunu kullanmanız lazım. Bu https://github.com/BLG638-Project/final-project-2022/commit/373f39153d2cbe3f5946c29b9b469ef37d97c039 commit'ten güncel linke ulaşabilirsiniz.

Teşekkürler.

**Comment by resuldagdanov** [comment]
simstarEnv.py kodunda **242**. satırda:

>         # attach appropriate sensors to the vehicle
>         track_sensor_settings = simstar.DistanceSensorParameters(
>             enable=True,
>             draw_debug=False,
>             add_noise=False,
>             position=simstar.PositionRPC(0.0, 0.0, -0.90),
>             orientation=simstar.OrientationRPC(0.0, 0.0, 0.0),
>             minimum_distance=0.2,
>             maximum_distance=200.0,
>             fov=190.0,
>             update_frequency_in_hz=60.0,
>             number_of_returns=self.track_sensor_size,
>             query_type=simstar.QueryType.Static,
>         )

_draw_debug_ parametresini **True** yaparsaniz sensor ciktilarini görselleştirebilirsiniz.

**NOTE:** yalnız _track_ sensörünün konumundan dolayı görsel olarak görülemeyebilir ama _opponents_ sensöründe çıktılar **daha iyi** görünecektir.

**Comment by resuldagdanov** [comment]
**Note:** Benzer sorun https://github.com/BLG638-Project/final-project-2022/issues/24 issue'da belirtilmiş ve açıklanmıştır.
