### ISSUE TITLE
Sensör Olası Hata

### ISSUE THREAD

**Issue by Aeunal** [BLG638-Project/final-project-2022#24]
İyi Günler, 
Sensörlerden gelen çıktıları görselleştirdiğimde olası hatalar olabileceğini saptadım, bunları aşağıya listeliyorum. Bu sonuçlara görselleştirme yaparak vardığım için yanlış yorumlamış olabilirim.

- Track sensor 19 tane uzaklık ölçüyor ama gördüğüm kadarıyla bunların 10 tanesi sol taraf, 9 tanesi sağ tarafı ölçüyor. Yani direk karşıyı 0 açısıyla ölçen bir data gelmiyor (bu da aracın duvarın ne zaman yaklaştığını görmesini çok zorlaştıran bir durum). Bu datalar (-95, -85, ..., -15, -5, 5, 15, ..., 75, 85) şeklinde açılara sahip görünüyor.
- Opponents sensörde 25 derece civarında sola doğru sapma görüyorum. Yani sol arka tarafımızı görebilirken, sağ arka ya da direk sağ tarafımızı göremiyoruz. 
- Opponents sensörünün ışınları arasındaki açı verilen şekilde 12 değil de 6 gibi görünüyor (yani fov verilenden daha küçük bir değermiş gibi). 
-  speedY her zaman pozitif dönüyor, araç sağa doğru da kaysa sola doğru da (normal olabilir)
- Pistin bazı noktalarında (ilk s dönüşten biraz sonrası gibi, yaklaşık 2-3 farklı yerde) angle verisi 180 derece hata ile geliyor.

Gereken bir bilgi olursa sağlayabilirim. 
Kolay Gelsin,
Ahmet Emin

**Comment by resuldagdanov** [comment]
Sayın @Aeunal,

Karşılaştığınız bu potansiyel hataları tespit ediyoruz ve çözümleri için uğraşıyoruz.

Teşekkürler.

**Comment by resuldagdanov** [comment]
Merhabalar,

* **Track Sensor:** asagidaki imajdan track sensörünün tam nereye baktığını gorebilirsiniz. Bu bir hata değil, tasarım seçeneğidir. Önceki yıllarda da aynı sensör tasarımı kullanılmiştır. Yarışma kapsamında herkes aynı koşullarda yarışacağı için bu sensör ile calişmanız uygun olacaktır.

![track_sensor](https://user-images.githubusercontent.com/60505033/174148372-0dd2e252-e088-422b-b110-2eaefb08d388.png)

* **Opponent Sensor:** Bu sensörün nereye baktığını görmek için _simstarEnv.py_ kodunda **242**. satırdaki _draw_debug_ parametresini geçici olarak **True** yaparak gözlemleyebilirsiniz. Yine daha önceki testlerden sensörun bu tasarımı uygun görüldüğü icin bununla devam etmeniz uygundur.

![opponents_sensor](https://user-images.githubusercontent.com/60505033/174150264-0663c929-1eda-4dd2-b61d-3b884c82a086.png)

```python
track_sensor_settings = simstar.DistanceSensorParameters(
enable=True,
draw_debug=True,
add_noise=False,
position=simstar.PositionRPC(0.0, 0.0, -0.90),
orientation=simstar.OrientationRPC(0.0, 0.0, 0.0),
minimum_distance=0.2,
maximum_distance=200.0,
fov=190.0,
update_frequency_in_hz=60.0,
number_of_returns=self.track_sensor_size,
query_type=simstar.QueryType.Static)
```

* **Angle Sensör:** Bu sensörün verisi ile ilgili testler devam etmektedir. Henuz bir sorun olup olmadığını dogrulayamadık.

**Comment by resuldagdanov** [comment]
**Ek:**
Sayın @Aeunal,

_Angle_ sensöründen kaynaklanan bahsettiğiniz sorunlar **giderilmiştir**. Düzeltilme https://github.com/BLG638-Project/final-project-2022/commit/ce346f23ff407543181b75b64460d7ffab7bc2a0 commit olarak güncellenmiştir.

Teşekkürler.
