### ISSUE TITLE
Proje ile ilgili detay soruları

### ISSUE THREAD

**Issue by Aeunal** [BLG638-Project/final-project-2022#25]
İyi Günler,
Yarışma/proje ile ilgili (genellikle çim ile ilgili) bir kaç sorum olacaktı. 

- Çim üzerinden gidilebiliyor mu, çim üzerinden gidilirse puan kırılıyor mu, yarışmada da track_pos değeri +1/-1 değerlerine ulaşınca diskalifiye mi olacağız, eğer diskalifiye olunmuyorsa training sürecinde bu track_pos'a göre sıfırlama değeri ile oynayabilir miyiz?
- Çim üzerinden ya da yol kenarlarından gidildiğinde araç hızına bir etkisi oluyor mu? (daha yavaşlatma gibi)
- Aracımız geri geri gidebiliyor mu? (aksiyonlardan gidemiyor olarak düşünüyorum ama kötü çalışan bir araca çarpılırsa gerekli olabilir)
- Eğer çim üzerinden gidilince diskalifiye olunmuyorsa engellere takıldığımızda aracın tekrar yola girmesini sağlamamız mı bekleniyor? (Bu durumları da curriculum learning senaryolarına eklemek gerekebilir ama geri gidilmiyorsa olmaz sanırım.)    
- Eğer çim üzerinden gidilince diskalifiye olunuyorsa diğer araçları çime itecek şekilde modelimizi geliştirmek yanlış olur mu? (Ters yoldan gidip karşımıza gelenleri diskalifiye ettikten sonra normal şekilde tamamlamak gibi 🤣) 
- Engelleri ya da diğer araçları yavaşlamak için kullanabiliyor muyuz?
- Reward fonksiyonunu oluştururken sadece ulaşabildiğimiz sensör datalarını mı kullanmalıyız yoksa simstarEnv üzerinden alabildiğimiz her türlü datayı kullanabiliyor muyuz?
- Aracımız vites atıyor mu, atıyorsa genelde oyunlardaki otomatik vitesler gibi mi çalışıyor? (belirli bir hıza gelindiğinde vites atış sekansının başlatılıp bu süreç zarfında hızın biraz düşmesi gibi) Bu datayı reward fonksiyonunda kullanmak için env üzerinden ulaşabiliyor muyuz?

Zaman ayırdığınız için teşekkürler,
Ahmet Emin

**Comment by resuldagdanov** [comment]
Sayın @Aeunal,

* Tüm arabalar çim üzerinde gidebilir ancak çimde giderken sürtünmeden dolayı yavaş hızlanacak ve belirli bir hızın üzerine çıkamayacaktır. _TrackPos_ değeri **1.0**'dan daha büyük olduğu zaman arabalar yoldan çıkmış sayılacaklardır ve hareketleri kısıtlanacaktır.
* Arabalar yol kenarında çim üzerine ilerlerken _sürtünmeden_ dolayı hızlarında **yavaşlama** oluyor.
* Araçların geri vitesleri yoktur ve **geri gidemezler**. Yol genişliği oldukça geniş olup olası çarpışma durumlarında tekrar yolun güzergahına girilebilir. Yarışmanın amaçlarından biri de sabit duran araçlardan **kaçınabilmeyi** öğrenmektir.
* Araçların **TrackPos > 1.0** koşulu sağlanmadığı sürece yarışmalarına müdahale **edilmez** ve diskalifiye **olunmaz**.
* Yarışma kurallarına uymak şartıyla istediğiniz taktiksel ajanlar öğretebilirsiniz. Dersin amacı mantıklı, avantajlı RL agent öğrenebilmektir / eğitebilmektir.
* Eğitim aşamasında reward fonksiyonunu istediğiniz gibi tasarlayabilirsiniz / kullanabilirsiniz. Ancak yarışma esnasında (evaluation) bu fonksiyon **devredışı** bırakılacaktır ve sadece model çıktıları araçlara uygulanacaktır.
* Araçlarda **vites yoktur**, dolayısıyla hızlanma esnasında vites değişimindeki yavaşlanma **gözlemlenmemektedir**.

Teşekkürler.

**Comment by Aeunal** [comment]
Zaman ayırıp cevapladığınız için çok teşekkür ederim. Benim için çok yararlı oldu.
