### ISSUE TITLE
Initialize Vehicles from Different Locations

### ISSUE THREAD

**Issue by resuldagdanov** [BLG638-Project/final-project-2022#28]
Hello,

In order to spawn vehicles from different locations, you can use the following function:

```python
self.vehicle = self.client.spawn_vehicle_to(
             vehicle_pose=simstar.PoseData(88.006317, -131.966187, yaw= np.deg2rad(146)),
             initial_speed=0,
             set_speed=0,
             vehicle_type=simstar.EVehicleType.F1Racing)
```

Latitude, longitude, and yaw angle (rotation angle) could be obtained from the SimStar simulation UI as shown below.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/60505033/174279862-23121228-b753-410a-8d50-c58c877273e5.png)

To get location information:
1) When the rendered simulation is opened, you can navigate to the desired location and by **clicking** on the track's intended position, the right bottom corner _visualizes_ details of **clicked position**.
2) Navigate ego vehicle to the desired location by keyboard control (https://github.com/BLG638-Project/final-project-2022/commit/c2de0417b6539983c4c79a7e89920bf92a4fc482) and comply the location information from the right bottom corner.

Thanks.

**Comment by afurkany** [comment]
Dear @resuldagdanov 

I might repeat my question but I want to ensure about your answer. We can use the below commands for only opponent vehicles, right? For the ego (agent) vehicle we need to use `spawn_vehicle()` function and it does not accept vehicle_pose argument as an input. Am I right?

```
self.vehicle = self.client.spawn_vehicle_to(
             vehicle_pose=simstar.PoseData(88.006317, -131.966187, yaw= np.deg2rad(146)),
             initial_speed=0,
             set_speed=0,
             vehicle_type=simstar.EVehicleType.F1Racing)
```

Many thanks!

**Comment by resuldagdanov** [comment]
Dear @afurkany,

You can spawn _all vehicles_ (**including ego vehicle** or main vehicle) with `spawn_vehicle_to()` function. To ensure that this is possible, please change the `simstarEnv.py` code lines **226-234** to the following code:

```python
self.main_vehicle = self.client.spawn_vehicle_to(
                vehicle_pose=simstar.PoseData(88.006317, -131.966187, yaw= np.deg2rad(146)),
                initial_speed=0,
                set_speed=0,
                vehicle_type=simstar.EVehicleType.F1Racing)
```

You will see that the ego vehicle (being trained RL agent) is spawned at the given `lat=88.006317, long=-131.966187, yaw=146` location.

Thanks.

**Comment by afurkany** [comment]
Dear @resuldagdanov

Thank you for the information. I think I made a mistake beforehand. It is working now.
