### ISSUE TITLE
Speed Up Parameter During Evaluation

### ISSUE THREAD

**Issue by MehmetcanKaymaz** [BLG638-Project/final-project-2022#29]
Hello,
What will be the **speed_up** parameter value during evaluation in final competition?
Thanks.

**Comment by resuldagdanov** [comment]
Dear @MehmetcanKaymaz,

As given in the `evaluate.py` **speed_up** is given as **2**, so during the final competition **`speed_up=2`** will be fixed for all competitors.
**Tip**: It is _recommended_ to train your model with **speed_up=2** fixed as the model will be evaluated with this configuration. From previous experiences, more stable trainings are achieved with speed_up=2 configuration.

Thanks.

**Comment by MehmetcanKaymaz** [comment]
Thanks @resuldagdanov
