### ISSUE TITLE
Tensor Shape of TD Loss

### ISSUE THREAD

**Issue by anilyerlikaya** [BLG638-Project/final-project-2022#30]
Hello,

I think, there is a problem with the calculation of losses in `sac_agent.py` because of the different shapes of tensors. IMHO, TD error (`backup`) should be a 1d tensor in the calculation of q_loss, however different shapes of `q_pi_target` [batch_size, 1] and `logp_next_action` [batch_size] lead it to be a 2d tensor [batch_size, batch_size]. The same thing also happens in the pi-loss calculation. When I look at other SAC agent implementations, I saw that their TD losses are 1d shape, so I wonder if these are just mistakes or something else that I don't know?

Thanks.

**Comment by resuldagdanov** [comment]
Dear @anilyerlikaya,

This is just an example. You can implement any algorithm you choose.

Thanks.
